"""
Daily Telegram News Digest Bot
------------------------------
Fetches the latest news on a topic (via GNews API), summarizes each article
into a punchy one-liner using Gemini, and sends a formatted digest to a
Telegram chat/group.

Required environment variables (set as GitHub Actions secrets, or in a local .env):
    TELEGRAM_BOT_TOKEN   - from @BotFather
    TELEGRAM_CHAT_ID     - the target group's chat id (e.g. -1001234567890)
    GNEWS_API_KEY        - from https://gnews.io
    GEMINI_API_KEY       - from https://aistudio.google.com/apikey (free tier)
    NEWS_TOPIC           - the topic to search for, e.g. "artificial intelligence"
                           (defaults to "technology" if not set)
"""

import os
import sys
import json
import requests
from datetime import datetime, timezone, timedelta

# ---------- Config ----------
GNEWS_MAX_ARTICLES = 5          # how many articles to pull from GNews
DIGEST_ARTICLE_COUNT = 5        # how many to include in the final digest (short format)
GEMINI_MODEL = "gemini-2.5-flash"  # fast, free-tier-friendly model
SGT = timezone(timedelta(hours=8))  # Singapore Time

TOPIC = os.environ.get("NEWS_TOPIC", "technology")
TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHAT_ID = os.environ["TELEGRAM_CHAT_ID"]
GNEWS_API_KEY = os.environ["GNEWS_API_KEY"]
GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]


def fetch_news(topic: str) -> list[dict]:
    """Fetch latest articles on a topic from GNews."""
    url = "https://gnews.io/api/v4/search"
    params = {
        "q": topic,
        "lang": "en",
        "max": GNEWS_MAX_ARTICLES,
        "sortby": "publishedAt",
        "token": GNEWS_API_KEY,
    }
    resp = requests.get(url, params=params, timeout=20)
    resp.raise_for_status()
    data = resp.json()
    return data.get("articles", [])


def summarize_articles(topic: str, articles: list[dict]) -> list[str]:
    """Use Gemini to generate one punchy summary sentence per article.

    Returns a list of plain-text summaries, in the same order as `articles`.
    URLs are NOT generated by the model — they're taken directly from the
    GNews data in build_digest() to avoid any risk of mismatched/incorrect links.
    """
    if not articles:
        return []

    articles_text = "\n\n".join(
        f"{i+1}. Title: {a['title']}\nDescription: {a.get('description', '')}"
        for i, a in enumerate(articles[:DIGEST_ARTICLE_COUNT])
    )

    prompt = f"""You are writing a short daily news digest about "{topic}".

Below are today's raw articles, numbered. For each one, write exactly ONE punchy,
informative sentence summarizing it (not just rephrasing the headline - pull out
the key fact).

Respond with ONLY a JSON array of strings, one per article, in the same order,
with no markdown formatting, no code fences, and no extra commentary. Example:
["Summary of article 1.", "Summary of article 2."]

Articles:
{articles_text}
"""

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent"
    headers = {"Content-Type": "application/json", "x-goog-api-key": GEMINI_API_KEY}
    payload = {"contents": [{"parts": [{"text": prompt}]}]}

    resp = requests.post(url, headers=headers, json=payload, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    raw_text = data["candidates"][0]["content"]["parts"][0]["text"].strip()

    # Strip accidental code fences, just in case the model adds them
    if raw_text.startswith("```"):
        raw_text = raw_text.strip("`")
        raw_text = raw_text.split("\n", 1)[-1] if raw_text.lower().startswith("json") else raw_text

    try:
        summaries = json.loads(raw_text)
    except json.JSONDecodeError:
        print(f"Warning: could not parse Gemini JSON output, falling back to raw text:\n{raw_text}", file=sys.stderr)
        # Fall back: one summary per line, in order
        summaries = [line.strip("- ").strip() for line in raw_text.splitlines() if line.strip()]

    return summaries


def build_digest(topic: str, articles: list[dict], summaries: list[str]) -> str:
    """Assemble the final Telegram message with today's date and real article URLs."""
    date_str = datetime.now(SGT).strftime("%d %B %Y")

    if not articles:
        return f"📰 *Daily {topic.title()} Digest* — {date_str}\n\nNo news found today for topic: {topic}"

    lines = [f"📰 *Daily {topic.title()} Digest* — {date_str}", ""]
    for i, article in enumerate(articles[:DIGEST_ARTICLE_COUNT]):
        summary = summaries[i] if i < len(summaries) else article["title"]
        lines.append(f"{i+1}. [{summary}]({article['url']})")
        lines.append("")  # blank line between articles

    return "\n".join(lines)


def send_to_telegram(text: str) -> None:
    """Send the digest to the configured Telegram chat."""
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": text,
        "parse_mode": "Markdown",
        "disable_web_page_preview": False,
    }
    resp = requests.post(url, json=payload, timeout=20)
    if not resp.ok:
        print(f"Telegram API error: {resp.status_code} {resp.text}", file=sys.stderr)
        resp.raise_for_status()


def main():
    print(f"Fetching news for topic: {TOPIC}")
    articles = fetch_news(TOPIC)
    print(f"Found {len(articles)} articles")

    summaries = summarize_articles(TOPIC, articles)
    digest = build_digest(TOPIC, articles, summaries)
    print("Digest generated:\n", digest)

    send_to_telegram(digest)
    print("Sent to Telegram successfully.")


if __name__ == "__main__":
    main()